version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: process.env.PRISMA_HOST
            database: process.env.PRISMA_DB
            user: process.env.PRISMA_USER
            password: process.env.PRISMA_PWD
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true